policy:
  approval:
    - unprotected
    - or:
        - "hk01-digital approved"
        - "dependabot doing security fix"
        - "hk01bot-write doing renovate"
  disapproval:
    requires:
      organizations:
        - hk01-digital
approval_rules:
  - name: unprotected
    requires:
      count: 0
  - name: hk01-digital approved
    if:
      targets_branch:
        pattern: ^development|^release|^master$
    options:
      allow_author: true
      allow_contributor: true
      invalidate_on_push: true
      ignore_update_merges: true
    requires:
      count: 1
      organizations:
        - hk01-digital
  - name: dependabot doing security fix
    if:
      only_changed_files:
        paths:
          - package.json
          - yarn.lock
          - package-lock.json
      has_author_in:
        users:
          - 'dependabot[bot]'
      only_has_contributors_in:
        users:
          - 'dependabot[bot]'
      targets_branch:
        pattern: development
    requires:
      count: 0
  - name: "hk01bot-write doing renovate"
    if:
      only_changed_files:
        paths:
          - package.json
          - package-lock.json
          - yarn.lock
      has_author_in:
        users:
          - hk01bot-write
      only_has_contributors_in:
        users:
          - hk01bot-write
          - renovate-bot
      targets_branch:
        pattern: development
    requires:
      count: 0
